#用户授权表
CREATE TABLE `USER_AUTH` (
  `ID` INT(20) NOT NULL AUTO_INCREMENT,
  `UID` INT(20) UNSIGNED NOT NULL DEFAULT '0' COMMENT '用户ID',
  `IDENTITY_TYPE` TINYINT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '0系统指定 1手机号 2邮箱 3用户名 4QQ 5微信 6腾讯微博 7新浪微博',
  `IDENTIFIER` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '手机号 邮箱 用户名或第三方应用的唯一标识',
  `CERTIFICATE` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '密码凭证(站内的保存密码，站外的不保存或保存TOKEN)',
  `CREATE_TIME` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '绑定时间',
  `UPDATE_TIME` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '更新绑定时间',
  STATUS TINYINT(4) UNSIGNED NOT NULL DEFAULT '1' COMMENT '状态 1正常 2注销(数据显示,不能登录) 3删除',
  USER_TYPE TINYINT(2) UNSIGNED NOT NULL DEFAULT '1' COMMENT '1正常用户 2测试用户 4虚拟用户 5运营',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ONLY` (`UID`,`IDENTITY_TYPE`),
  KEY `IDX_UID` (`UID`) USING BTREE
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COMMENT='用户授权表';

#用户基础信息
CREATE TABLE USER_BASE (
  `UID` INT(20) NOT NULL COMMENT '用户ID',
  `REGISTER_SOURCE` TINYINT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '注册来源：0系统指定 1手机号 2邮箱 3用户名 4QQ 5微信 6腾讯微博 7新浪微博',
  `USER_NAME` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户账号，必须唯一',
  `NICK_NAME` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户昵称',
  `GENDER` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '用户性别 0-FEMALE 1-MALE',
  `BIRTHDAY` INT(20) UNSIGNED NOT NULL DEFAULT '0' COMMENT '用户生日',
  `SIGNATURE` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '用户个人签名',
  `MOBILE` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '手机号码(唯一)',
  `MOBILE_BIND_TIME` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '手机号码绑定时间',
  `EMAIL` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '邮箱(唯一)',
  `EMAIL_BIND_TIME` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '邮箱绑定时间',
  `FACE` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '头像',
  `FACE200` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '头像 200X200X80',
  `SRCFACE` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '原图头像',
  `CREATE_TIME` INT(11) UNSIGNED NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` INT(11) UNSIGNED NOT NULL COMMENT '修改时间',
  `PUSH_TOKEN` VARCHAR(50) NOT NULL COMMENT '用户设备PUSH_TOKEN',
  PRIMARY KEY (`UID`),
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COMMENT='用户基础信息表';



#用户登陆日志
CREATE TABLE LOG_USER_LOGIN (
  `ID` INT(20) NOT NULL AUTO_INCREMENT,
  `UID` INT(20) UNSIGNED NOT NULL DEFAULT '0' COMMENT '用户UID',
  `TYPE` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1' COMMENT '登录方式 第三方/邮箱/手机等',
  `COMMAND` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1' COMMENT '操作类型 1登陆成功  2登出成功 3登录失败 4登出失败',
  `VERSION` VARCHAR(32) NOT NULL DEFAULT '1.0' COMMENT '客户端版本号',
  `CLIENT` VARCHAR(20) NOT NULL DEFAULT 'DABAOZHA' COMMENT '客户端',
  `DEVICE_ID` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '登录时设备号',
  `LASTIP` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '登录IP',
  `OS` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '手机系统',
  `OSVER` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '系统版本',
  `TEXT` VARCHAR(200) NOT NULL DEFAULT '',
  `CREATE_TIME` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '操作时间',
  PRIMARY KEY (`ID`),
  KEY `IDX_UID_TYPE_TIME` (`UID`,`TYPE`,`CREATE_TIME`) USING BTREE,
  KEY `IDX_CREATE_TIME` (`CREATE_TIME`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COMMENT='登陆日志表';
#用户注册日志
CREATE TABLE LOG_USER_REGISTER (
  `ID` INT(20) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `UID` INT(20) UNSIGNED NOT NULL COMMENT '用户ID',
  `REGISTER_METHOD` TINYINT(2) UNSIGNED NOT NULL COMMENT '注册方式1手机号 2邮箱 3用户名 4QQ 5微信 6腾讯微博 7新浪微博',
  `REGISTER_TIME` INT(11) NOT NULL COMMENT '注册时间',
  `REGISTER_IP` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '注册IP',
  `REGISTER_CLIENT` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '注册客户端',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=12 DEFAULT CHARSET=UTF8MB4 COMMENT='用户注册日志表';
#修改信息日志
CREATE TABLE UPDATE_USER_INFO (
  `ID` INT(20) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `UID` INT(20) UNSIGNED NOT NULL COMMENT '用户ID',
  `ATTRIBUTE_NAME` VARCHAR(30) NOT NULL COMMENT '属性名',
  `ATTRIBUTE_OLD_VAL` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '属性对应旧的值',
  `ATTRIBUTE_NEW_VAL` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '属性对应新的值',
  `UPDATE_TIME` INT(11) NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=12 DEFAULT CHARSET=UTF8MB4 COMMENT='用户注册日志表';

