#角色表
CREATE TABLE ROLE_INFO (
  ROLE_ID INT(20) NOT NULL AUTO_INCREMENT,
  ROLE_NAME VARCHAR(50) NOT NULL DEFAULT '' COMMENT '角色名',
  CREATE_TIME INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建时间',
  UPDATE_TIME INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '更新时间',
  STATUS TINYINT(4) UNSIGNED NOT NULL DEFAULT '1' COMMENT '状态 1正常 0删除',
  PRIMARY KEY (`ROLE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COMMENT='角色表';

#权限表
CREATE TABLE PERM_INFO (
  PERM_ID INT(20) NOT NULL AUTO_INCREMENT,
  PERM_NAME VARCHAR(50) NOT NULL DEFAULT '' COMMENT '权限名',
  PERM_TYPE TINYINT(4) UNSIGNED NOT NULL DEFAULT '0' COMMENT '权限类型：1菜单 2资源',
  URL VARCHAR(50) NOT NULL DEFAULT '' COMMENT '权限url路径',
  PARENT_ID INT(20) UNSIGNED NOT NULL DEFAULT '0' COMMENT '父ID',
  SORT SMALLINT(6) UNSIGNED NOT NULL DEFAULT '0' COMMENT '排序',
  LIMIT_IDS INT(20) UNSIGNED  COMMENT '完全限定IDS',
  REMARK VARCHAR(255) COMMENT '备注',
  CREATE_TIME INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建时间',
  UPDATE_TIME INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '更新时间',
  STATUS TINYINT(4) UNSIGNED NOT NULL DEFAULT '1' COMMENT '状态 1正常 0删除',
  PRIMARY KEY (`PERM_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COMMENT='权限表';

#角色权限中间表
CREATE TABLE ROLE_PERM_INFO (
  ID INT(20) NOT NULL AUTO_INCREMENT,
  ROLE_ID INT(20) NOT NULL DEFAULT '0',
  PERM_ID INT(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COMMENT='角色权限中间表';

#角色用户中间表
CREATE TABLE ROLE_USER_INFO (
  ID INT(20) NOT NULL AUTO_INCREMENT,
  ROLE_ID INT(20) NOT NULL DEFAULT '0',
  UID INT(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COMMENT='角色用户中间表';